from utils.env import read_positive_float, read_positive_int


ROUND_DURATION = read_positive_int("ROUND_DURATION", 60)
COUNTDOWN_DURATION = read_positive_int("COUNTDOWN_DURATION", 5)
ROUND_COUNTDOWN_DURATION = read_positive_int("ROUND_COUNTDOWN_DURATION", 3)
ROUND_WIN_TARGET = read_positive_int("ROUND_WIN_TARGET", 2)
ROUND_REPLAY_DURATION = read_positive_float("ROUND_REPLAY_DURATION", 8.0)
ROUND_REPLAY_FINAL_HOLD_DURATION = read_positive_float(
    "ROUND_REPLAY_FINAL_HOLD_DURATION", 3.0
)
SCORE_INCREMENT_PER_SECOND = read_positive_float("SCORE_INCREMENT_PER_SECOND", 0.5)
MATCHMAKING_RANGE_STEP = read_positive_int("MATCHMAKING_RANGE_STEP", 50)
MATCHMAKING_MAX_RANGE = read_positive_int("MATCHMAKING_MAX_RANGE", 600)
MATCHMAKING_WAIT_PER_STEP = read_positive_int("MATCHMAKING_WAIT_PER_STEP", 5)
REPLAY_MAX_STROKES = read_positive_int("REPLAY_MAX_STROKES", 128)
REPLAY_MAX_POINTS = read_positive_int("REPLAY_MAX_POINTS", 8192)
REPLAY_MAX_EVENTS = read_positive_int("REPLAY_MAX_EVENTS", 1024)
WS_DISCONNECT_GRACE_PERIOD = read_positive_float("WS_DISCONNECT_GRACE_PERIOD", 10.0)

if ROUND_REPLAY_FINAL_HOLD_DURATION >= ROUND_REPLAY_DURATION:
    raise ValueError("ROUND_REPLAY_FINAL_HOLD_DURATION must be shorter than ROUND_REPLAY_DURATION")
