services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: trsc_back
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    ports:
      - "8000:8000"
    networks:
      - trsc_net

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
    container_name: trsc_front
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/static:/app/static
      - /app/node_modules
    networks:
      - trsc_net

networks:
  trsc_net:
    driver: bridge
