services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: trsc_back
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    networks:
      - trsc_net

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx.Dockerfile
    container_name: trsc_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - trsc_net

networks:
  trsc_net:
    driver: bridge
